[unix_http_server]
file=/run/axon/supervisor.sock
chmod=0600

[supervisord]
nodaemon=true
logfile=/var/log/axon/supervisord.log
logfile_maxbytes=20MB
logfile_backups=5
pidfile=/run/axon/supervisord.pid
childlogdir=/var/log/axon
user=axon

[supervisorctl]
serverurl=unix:///run/axon/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

