# syntax=docker/dockerfile:1
FROM python:3.11-slim-bookworm
RUN groupadd -g 10005 axon-broker && useradd -u 10005 -g 10005 --no-create-home axon-broker
WORKDIR /opt/axon-broker
COPY --chown=root:root operational/broker.py /opt/axon-broker/broker.py
USER 10005:10005
ENTRYPOINT ["python", "/opt/axon-broker/broker.py"]
